openapi: "3.0.3"
info:
  title: Room Information Management System
  version: 1.0.0
servers:
  - url: http://localhost:8081/

paths:
  /rooms:
    get:
      tags:
        - rooms
      operationId: getRooms
      summary: Get all rooms
      responses:
        200:
          description: Get all rooms successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Room'
    post:
      tags:
        - rooms
      operationId: createRoom
      summary: Create a room
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Room'
      responses:
        201:
          description: Create room information successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Room'

  /rooms/{roomId}:
    get:
      tags:
        - rooms
      operationId: getRoom
      summary: Info for a specific room
      parameters:
        - name: roomId
          in: path
          description: "Id of the room"
          required: true
          schema:
            type: string
      responses:
        200:
          description: Get room information successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Room'

components:
  schemas:
    Room:
      type: object
      required:
        - address
      properties:
        id:
          type: integer
          format: int64
        address:
          type: string
